---
title: "Group 48 UCSB domestic grad enrollment"
author: "Shuying Yu and Kiera Matiska"
date: "11/15/2021"
output: html_document
---

```{r setup, include = TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

#Attach packages
library(tidyverse)
library(here)
```


# Read in the data

Use the `read_csv()` fuction and the `here` package to read in ucsb_grad_data.csv

```{r}
#Read in data
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```

# Visualize Data

Create a column graph showing the change in domestic enrollment (y-axis: `domestic_enrollment`) by year from 2008 - 2019 (x-axis: `year_abbr`)

- Graph should be fill colored by ethnicity
- Convert column counts to proportions

```{r}
#Column plot
ggplot(data = ucsb_grad,
       aes(x = year_abbr, y = domestic_enrollment)) +
  
  #Define column
  #Color by ethnicity
  #Convert column counts to proportions
  geom_col(aes(fill = ethnicity),
           position = "fill") +
  
  #Change x-axis and y-axis labels
  labs(x = "Year \n(abbreivated)",
       y = "Domestic Graduate Enrollment at UCSB (%)")
```

